name: LimboCrates
version: 0.0.1-beta
api: 5.0.0
main: Taskov1ch\LimboCrates\Main
softdepend:
  - WFT

permissions:
  limbo.crates.addkeys:
    default: op
  limbo.crates.takekeys:
    default: op
  limbo.crates.mykeys:
    default: true
  limbo.crates.createcrate:
    default: op
  limbo.crates.deletecrate:
    default: op
